platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Post Install processing for Flipper
def flipper_post_install(installer)
  file_name = Dir.glob("*.xcodeproj")[0]
  app_project = Xcodeproj::Project.open(file_name)
  app_project.native_targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited) '
      unless cflags.include? '-DFB_SONARKIT_ENABLED=1'
        puts 'Adding -DFB_SONARKIT_ENABLED=1 in OTHER_CFLAGS...'
        cflags << '-DFB_SONARKIT_ENABLED=1'
      end
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
    app_project.save
  end
  installer.pods_project.save
end

def base_pods

end

target 'Target' do
  # Pods for Target
  base_pods

  target 'TargetTests' do
    inherit! :complete
    # Pods for testing
  end

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Target-Staging' do
  # Pods for Target
  base_pods
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Target-QA' do
  # Pods for Target
  base_pods
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Target-Develop' do
  # Pods for Target
  base_pods
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Target-tvOS' do
  # Pods for Target-tvOS
  
  target 'Target-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end

# Flipper doesn't build with Xcode 12.5. See: https://github.com/facebook/flipper/issues/2215
# Temporary solution:
# `use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.75.1', 'Flipper-RSocket' => '1.3.1' })`
# instead of `use_flipper!`

use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})

post_install do |installer|
  flipper_post_install(installer)
end
